"""message

Revision ID: ad773ba2f7f8
Revises: db3b3e131c9e
Create Date: 2022-05-30 08:31:59.926506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad773ba2f7f8'
down_revision = 'db3b3e131c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
