"""message

Revision ID: db3b3e131c9e
Revises: 79d63ac5adab
Create Date: 2022-05-30 07:33:06.705001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3b3e131c9e'
down_revision = '79d63ac5adab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('probability', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'probability')
    # ### end Alembic commands ###
